# Generated by Django 4.1.5 on 2023-01-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('imag', models.ImageField(upload_to='')),
                ('aimg', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('imag', models.ImageField(upload_to='')),
                ('aimg', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('imag', models.ImageField(upload_to='')),
                ('aimg', models.ImageField(upload_to='')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr.block')),
                ('clg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr.college')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='clg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr.college'),
        ),
    ]
