# Generated by Django 4.1.5 on 2023-01-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_block_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='lower',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='upper',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
